map $http_upgrade $connection_upgrade {
    default Upgrade;
    ''      close;
}

upstream backend_servers {
    # ip_hash ensures Sticky Sessions for SignalR
    ip_hash;
    server backend-1:8080;
    server backend-2:8080;
}

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Frontend Assets
    location / {
        try_files $uri /index.html;
    }

    # API Proxy
    location /api {
        proxy_pass http://backend_servers;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # SignalR Hubs Proxy (Important for Bidding)
    location /hubs {
        proxy_pass http://backend_servers;
        proxy_http_version 1.1;

        # SignalR require WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Buffering should be off for SignalR
        proxy_buffering off;
        proxy_read_timeout 3600s;
    }
}